//! FleetWorkflow (build stage C, triumvirate-fleet-BUILD.md; design triumvirate-fleet.md).
//!
//! Workflow ID = the fleet ID, generated by the client before start (never inside workflow
//! code). Steps, every one an activity so the workflow itself stays deterministic:
//! 1. `prepare_fleet`: ledger rows, worktrees, task files, events (the SAME function the legacy
//!    engine uses, idempotent), marks the fleet as Temporal-owned, builds each member's command.
//! 2. `run_worker` per member, in parallel (stage B: fresh, adopt or finished).
//! 3. `record_task_outcome` per member (the SAME recording as legacy).
//! 4. `finalize_fleet`: the legacy terminal check, which runs the merge and the review gate.
//!
//! Cancellation: running members are cancelled (their activities stop their verified groups),
//! then `cancel_cleanup` runs on a token the workflow's cancellation cannot reach: it stops any
//! verified worker still running and marks the ledger cancelled. The workflow then ends CANCELED.

use std::{path::PathBuf, time::Duration};

use fleet::{git_ops::RealGitOps, orchestrator::FleetOrchestrator, worker_token};
use serde::{Deserialize, Serialize};
use shared_types::GitOps;
use temporalio_macros::{activities, workflow, workflow_methods};
use temporalio_sdk::{
    ActivityExecutionError, ActivityOptions, WorkflowCancellationToken, WorkflowContext, WorkflowContextView,
    WorkflowResult, WorkflowTermination,
    activities::{ActivityContext, ActivityError},
};

use crate::{
    FleetActivities, run_worker_options,
    worker::{RunWorkerInput, RunWorkerOutput},
};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FleetInput {
    pub fleet_id: String,
    pub project_root: String,
    pub agents: Vec<String>,
    pub task_description: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MemberStatus {
    pub task_id: String,
    pub agent: String,
    /// pending | running | done | failed | cancelled
    pub state: String,
    pub exit_code: Option<i32>,
    pub adopted: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FleetResult {
    /// The fleet's ledger state after finalize (done, failed, blocked_on_review, ...).
    pub ledger_state: String,
    pub members: Vec<MemberStatus>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskOutcome {
    pub project_root: String,
    pub fleet_id: String,
    pub task_id: String,
    pub agent: String,
    pub output: Option<RunWorkerOutput>,
    pub error: Option<String>,
}

/// Cheap, idempotent ledger and git I/O: a few retries, never unbounded.
fn io_options() -> ActivityOptions {
    ActivityOptions::with_start_to_close_timeout(Duration::from_secs(300))
        .retry_policy(
            temporalio_common::RetryPolicy::builder()
                .initial_interval(Duration::from_secs(2))
                .maximum_attempts(3)
                .build(),
        )
        .build()
}

#[workflow]
#[derive(Default)]
pub struct FleetWorkflow {
    members: Vec<MemberStatus>,
}

/// Why a fleet run stopped short. Every abort, from ANY step, goes through `abort_fleet`, so a
/// crash, a failure or a cancel can no longer leave the fleet Temporal-owned and `running` with
/// no one to finish it (Grok, review of 3871850).
struct Abort {
    cancelled: bool,
    reason: String,
    /// The failure to end the workflow with; None for a cancel.
    error: Option<ActivityExecutionError>,
}

fn abort(e: ActivityExecutionError) -> Abort {
    let cancelled = matches!(e, ActivityExecutionError::Cancelled(_));
    Abort { cancelled, reason: e.to_string(), error: (!cancelled).then_some(e) }
}

/// Options for steps that must run even after the workflow is cancelled: recording outcomes that
/// already happened, and the abort cleanup. A token the workflow's cancellation cannot reach.
fn detached(opts_timeout: Duration) -> ActivityOptions {
    ActivityOptions::with_start_to_close_timeout(opts_timeout)
        .cancellation_token(WorkflowCancellationToken::new())
        .retry_policy(
            temporalio_common::RetryPolicy::builder()
                .initial_interval(Duration::from_secs(2))
                .maximum_attempts(3)
                .build(),
        )
        .build()
}

#[workflow_methods]
impl FleetWorkflow {
    #[run(name = "triumvirate-fleet")]
    pub async fn run(ctx: &mut WorkflowContext<Self>, input: FleetInput) -> WorkflowResult<FleetResult> {
        match Self::drive(ctx, &input).await {
            Ok(result) => Ok(result),
            Err(a) => {
                let cancelled = a.cancelled || ctx.cancellation_token().is_cancelled();
                ctx.state_mut(|s| {
                    for m in s.members.iter_mut().filter(|m| m.state == "running" || m.state == "pending") {
                        m.state = if cancelled { "cancelled" } else { "failed" }.to_string();
                    }
                });
                ctx.execute_activity(
                    FleetLedgerActivities::abort_fleet,
                    AbortInput { fleet: input, cancelled, reason: a.reason.clone() },
                    detached(Duration::from_secs(180)),
                )
                .await?;
                match a.error {
                    Some(e) if !cancelled => Err(e.into()),
                    _ => Err(WorkflowTermination::cancelled()),
                }
            }
        }
    }

    async fn drive(ctx: &mut WorkflowContext<Self>, input: &FleetInput) -> Result<FleetResult, Abort> {
        let plans = ctx
            .execute_activity(FleetLedgerActivities::prepare_fleet, input.clone(), io_options())
            .await
            .map_err(abort)?;
        ctx.state_mut(|s| {
            s.members = plans
                .iter()
                .map(|p| MemberStatus {
                    task_id: p.task_id.clone(),
                    agent: p.agent.clone(),
                    state: "running".to_string(),
                    exit_code: None,
                    adopted: false,
                })
                .collect();
        });

        let runs: Vec<_> = plans
            .iter()
            .cloned()
            .map(|p| ctx.execute_activity(FleetActivities::run_worker, p, run_worker_options()))
            .collect();
        let results = temporalio_sdk::workflows::join_all(runs).await;

        // Record EVERY member that finished, success or failure, before acting on a cancel: an
        // outcome that already happened must reach the ledger whatever happens next (a failed
        // member was dropped when another was cancelled: Grok, review of 3871850). Detached, so
        // a cancel cannot stop the recording of what already happened.
        let mut cancelled: Option<ActivityExecutionError> = None;
        for (plan, result) in plans.iter().zip(results) {
            let (output, error) = match result {
                Ok(o) => (Some(o), None),
                Err(e @ ActivityExecutionError::Cancelled(_)) => {
                    cancelled.get_or_insert(e);
                    continue;
                }
                Err(e) => (None, Some(e.to_string())),
            };
            let outcome = TaskOutcome {
                project_root: input.project_root.clone(),
                fleet_id: input.fleet_id.clone(),
                task_id: plan.task_id.clone(),
                agent: plan.agent.clone(),
                output: output.clone(),
                error,
            };
            let state = ctx
                .execute_activity(FleetLedgerActivities::record_task_outcome, outcome, detached(Duration::from_secs(120)))
                .await
                .map_err(abort)?;
            ctx.state_mut(|s| {
                if let Some(m) = s.members.iter_mut().find(|m| m.task_id == plan.task_id) {
                    m.state = state.clone();
                    m.exit_code = output.as_ref().and_then(|o| o.exit_code);
                    m.adopted = output.as_ref().is_some_and(|o| o.adopted);
                }
            });
        }
        if let Some(e) = cancelled {
            return Err(abort(e));
        }
        // A cancel that arrived after every member finished: their outcomes are recorded above;
        // the merge must not run for a cancelled fleet.
        if ctx.cancellation_token().is_cancelled() {
            return Err(Abort { cancelled: true, reason: "cancelled after every member finished".to_string(), error: None });
        }

        let ledger_state = ctx
            .execute_activity(FleetLedgerActivities::finalize_fleet, input.clone(), io_options())
            .await
            .map_err(abort)?;
        Ok(FleetResult { ledger_state, members: ctx.state(|s| s.members.clone()) })
    }

    /// Per-member state from workflow memory. `fleet_status` reads this for Temporal fleets.
    #[query]
    pub fn status(&self, _ctx: &WorkflowContextView) -> Vec<MemberStatus> {
        self.members.clone()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AbortInput {
    pub fleet: FleetInput,
    pub cancelled: bool,
    pub reason: String,
}

fn app_err(e: impl std::fmt::Display) -> ActivityError {
    anyhow::anyhow!("{e}").into()
}

pub struct FleetLedgerActivities;

#[activities]
impl FleetLedgerActivities {
    /// Prepare every member (shared, idempotent legacy code), mark the fleet as Temporal-owned,
    /// and return each member's run_worker input.
    #[activity(name = "triumvirate-prepare-fleet")]
    pub async fn prepare_fleet(_ctx: ActivityContext, input: FleetInput) -> Result<Vec<RunWorkerInput>, ActivityError> {
        let root = PathBuf::from(&input.project_root);
        let git = RealGitOps::new(root.clone()).map_err(app_err)?;
        let head = git.current_head().await.map_err(app_err)?;
        let orch = FleetOrchestrator::new(git);
        // Marked BEFORE any worker can exist, so legacy recovery never treats it as crashed.
        worker_token::mark_temporal_engine(&root, &input.fleet_id).map_err(app_err)?;
        let members = orch
            .prepare_fleet_members(&root, &input.fleet_id, &head, &input.agents, &input.task_description)
            .await
            .map_err(app_err)?;
        let mut out = Vec::new();
        for m in members {
            out.push(RunWorkerInput {
                project_root: input.project_root.clone(),
                fleet_id: input.fleet_id.clone(),
                task_id: m.task_id,
                agent: m.agent.clone(),
                worktree: m.worktree.display().to_string(),
                command: member_command(&m.agent, &m.worktree, &m.prompt).map_err(app_err)?,
            });
        }
        Ok(out)
    }

    /// Record one member's outcome the legacy way. Returns the member's new state.
    #[activity(name = "triumvirate-record-task-outcome")]
    pub async fn record_task_outcome(_ctx: ActivityContext, o: TaskOutcome) -> Result<String, ActivityError> {
        let root = PathBuf::from(&o.project_root);
        let succeeded = o.output.as_ref().is_some_and(|out| out.exit_code == Some(0));
        let payload = serde_json::json!({
            "task_id": o.task_id,
            "agent": o.agent,
            "requested_agent": o.agent,
            "engine": "temporal",
            "exit_code": o.output.as_ref().and_then(|x| x.exit_code),
            "signal": o.output.as_ref().and_then(|x| x.signal),
            "branch_head": o.output.as_ref().and_then(|x| x.branch_head.clone()),
            "adopted": o.output.as_ref().is_some_and(|x| x.adopted),
            "error": o.error,
        });
        if succeeded {
            fleet::orchestrator::record_task_completed(&root, &o.fleet_id, &o.task_id, &o.agent, payload);
            Ok("done".to_string())
        } else {
            fleet::orchestrator::record_task_failed(&root, &o.fleet_id, &o.task_id, payload);
            Ok("failed".to_string())
        }
    }

    /// The legacy terminal check: merges completed branches through the review gate, or fails
    /// the fleet. Returns the ledger state it leaves.
    #[activity(name = "triumvirate-finalize-fleet")]
    pub async fn finalize_fleet(_ctx: ActivityContext, input: FleetInput) -> Result<String, ActivityError> {
        let root = PathBuf::from(&input.project_root);
        let orch = FleetOrchestrator::new(RealGitOps::new(root.clone()).map_err(app_err)?);
        orch.finalize_if_all_tasks_terminal(&input.fleet_id, &root).await;
        let (state, _) = fleet::orchestrator::fleet_ledger_snapshot(&root, &input.fleet_id)
            .ok_or_else(|| app_err(format!("no ledger row for {}", input.fleet_id)))?;
        Ok(state)
    }

    /// The one cleanup for every abort, cancel or failure, at any step. Stops any verified worker
    /// still running; then marks the ledger cancelled or failed and fails any task left in
    /// flight. If a worker cannot be PROVEN stopped it refuses to mark anything: claiming
    /// `cancelled` while an agent may still run is the lie this engine exists to end (Grok,
    /// review of 3871850). Then the workflow fails with that error instead.
    #[activity(name = "triumvirate-abort-fleet")]
    pub async fn abort_fleet(_ctx: ActivityContext, a: AbortInput) -> Result<String, ActivityError> {
        let root = PathBuf::from(&a.fleet.project_root);
        let fleet_id = &a.fleet.fleet_id;
        let report = fleet::orchestrator::stop_fleet_workers(&root, fleet_id, Vec::new(), fleet::orchestrator::fleet_kill_grace()).await;
        if !report.problems.is_empty() {
            tracing::error!(fleet_id = %fleet_id, problems = ?report.problems, "abort: a worker may still be running; ledger left as it is");
            return Err(ActivityError::Application(Box::new(temporalio_sdk::ApplicationFailure::non_retryable(format!(
                "fleet {fleet_id} could not be stopped cleanly; workers may still run: {}",
                report.problems.join("; ")
            )))));
        }
        let state = if a.cancelled { "cancelled" } else { "failed" };
        let reason = if a.cancelled {
            "cancelled through the Temporal engine".to_string()
        } else {
            format!("Temporal engine: {}", a.reason.chars().take(500).collect::<String>())
        };
        let db = root.join(".triumvirate").join("ledger.db");
        let conn = rusqlite::Connection::open(&db).map_err(app_err)?;
        conn.execute(
            "UPDATE fleets SET state = ?2, failure_reason = ?3
             WHERE fleet_id = ?1 AND state NOT IN ('done', 'failed', 'cancelled')",
            rusqlite::params![fleet_id, state, reason],
        )
        .map_err(app_err)?;
        conn.execute(
            "UPDATE tasks SET state = 'failed'
             WHERE fleet_id = ?1 AND state IN ('pending', 'claimed', 'in_progress')",
            rusqlite::params![fleet_id],
        )
        .map_err(app_err)?;
        Ok(state.to_string())
    }
}

/// A member's command line. Real agents come from the one shared builder. `stub` exists only for
/// the exit checks and only when TRIUMVIRATE_FLEET_STUB_SCRIPT is set: it runs that script with sh.
fn member_command(agent: &str, worktree: &std::path::Path, prompt: &str) -> anyhow::Result<Vec<String>> {
    if agent == "stub" {
        let script = std::env::var("TRIUMVIRATE_FLEET_STUB_SCRIPT")
            .map_err(|_| anyhow::anyhow!("agent 'stub' requires TRIUMVIRATE_FLEET_STUB_SCRIPT (exit checks only)"))?;
        return Ok(vec!["sh".to_string(), "-c".to_string(), script]);
    }
    let (cmd, args) = fleet::orchestrator::fleet_agent_command(agent, worktree, prompt)?;
    Ok(std::iter::once(cmd).chain(args).collect())
}
