#!/bin/bash
# send.sh - Main script for send-to-claude skill
# Sends properly formatted inter-agent request to Claude (using OPUS model)

set -euo pipefail

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"

# Default values
REQUEST_TYPE="question"
CONTEXT="Full context in session log"
QUESTION=""
SESSION_LOG_OVERRIDE=""
NO_COMMIT=false
MODEL="opus"  # CRITICAL: Use Opus for inter-agent requests to Claude
HEADLESS=false

# Detect which agent we are
CURRENT_AGENT="unknown"
if [[ -f ~/.gemini/GEMINI.md ]]; then
    CURRENT_AGENT="gemini"
elif [[ -f ~/.codex/AGENTS.md ]]; then
    CURRENT_AGENT="codex"
fi

# Parse arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --type)
                REQUEST_TYPE="$2"
                shift 2
                ;;
            --context)
                CONTEXT="$2"
                shift 2
                ;;
            --session-log)
                SESSION_LOG_OVERRIDE="$2"
                shift 2
                ;;
            --no-commit)
                NO_COMMIT=true
                shift
                ;;
            --model)
                MODEL="$2"
                shift 2
                ;;
            --headless)
                HEADLESS=true
                shift
                ;;
            --help)
                show_help
                exit 0
                ;;
            *)
                # Treat as question
                QUESTION="$1"
                shift
                ;;
        esac
    done
}

# Show help
show_help() {
    cat <<EOF
Usage: send-to-claude [OPTIONS] "QUESTION"

Send an inter-agent request to Claude using the standardized protocol.

OPTIONS:
    --type TYPE           Request type: question, review, debug, architecture, other
                         (default: question)
    --context TEXT       Brief context summary (default: "Full context in session log")
    --session-log PATH   Override session log path (default: auto-detect)
    --no-commit          Skip git commit of session log
    --model MODEL        Claude model to use (default: opus)
    --headless           Disable interactive prompts; fail if QUESTION is missing
    --help               Show this help message

EXAMPLES:
    send-to-claude "How should I structure this Supabase function?"
    send-to-claude --type review "Review this edge function"
    send-to-claude --context "Tried RLS and app-level" "Which is better?"

NOTE: Uses Claude Opus model by default for inter-agent requests.

EOF
}

# Create minimal session log if it doesn't exist
create_session_log() {
    local session_log_path="$1"
    local taxonomy="$2"

    # Extract components from taxonomy
    IFS='/' read -r owner client domain repo <<< "$taxonomy"

    mkdir -p "$(dirname "$session_log_path")"

    cat > "$session_log_path" <<EOF
# Session Log: $taxonomy

**Agent:** $CURRENT_AGENT
**Feature:** inter-agent-request
**Generated:** $(TZ='America/New_York' date '+%Y-%m-%d %H:%M:%S %Z')

---

## CONTEXT SUMMARY

### Goal
Send inter-agent request to Claude.

### Current State
Awaiting Claude's response.

### Session Activity
- $(TZ='America/New_York' date '+%H:%M') - Created session log for inter-agent request

---

## INSTRUCTIONS FOR NEXT SESSION

This session log was auto-generated by the send-to-claude skill.
Update with relevant context as needed.
EOF

    echo "✅ Created session log: $session_log_path" >&2
}

# True when script should avoid interactive prompts.
is_headless_mode() {
    [[ "$HEADLESS" == true ]] || [[ "${CI:-}" == "true" ]] || [[ ! -t 0 ]] || [[ ! -t 1 ]]
}

# Resolve QUESTION automatically for headless runs.
hydrate_question_for_headless() {
    if [[ -n "$QUESTION" ]]; then
        return 0
    fi

    # If stdin is piped, use it as the question body.
    if [[ ! -t 0 ]]; then
        local stdin_question=""
        stdin_question="$(cat)"
        # Trim leading/trailing whitespace-only content check.
        if [[ -n "${stdin_question//[[:space:]]/}" ]]; then
            QUESTION="$stdin_question"
            return 0
        fi
    fi

    QUESTION="Please review the linked session log and provide actionable guidance."
}

# Main function
main() {
    parse_args "$@"

    # Interactive mode if no question provided
    if [[ -z "$QUESTION" ]]; then
        if is_headless_mode; then
            hydrate_question_for_headless
            echo "ℹ️  Headless mode: QUESTION not provided, using auto-resolved question." >&2
            echo "   Override by passing QUESTION as an argument." >&2
        else
            echo "📝 Interactive mode - Enter request details:" >&2
            echo -n "Request type [question]: " >&2
            read -r input_type
            if [[ -n "$input_type" ]]; then
                REQUEST_TYPE="$input_type"
            fi

            echo -n "Question: " >&2
            read -r QUESTION

            if [[ -z "$QUESTION" ]]; then
                echo "❌ Error: Question is required" >&2
                exit 1
            fi

            echo -n "Context (optional): " >&2
            read -r input_context
            if [[ -n "$input_context" ]]; then
                CONTEXT="$input_context"
            fi
        fi
    fi

    # Detect context
    echo "🔍 Detecting context..." >&2
    local context_json
    context_json=$("$SCRIPT_DIR/detect-context.sh")

    # Update FROM and TO fields
    context_json=$(echo "$context_json" | jq --arg from "$CURRENT_AGENT" --arg to "claude" '.from = $from | .to = $to')

    # Add request_type to JSON
    context_json=$(echo "$context_json" | jq --arg rt "$REQUEST_TYPE" '. + {request_type: $rt}')

    # Override session log if provided
    if [[ -n "$SESSION_LOG_OVERRIDE" ]]; then
        context_json=$(echo "$context_json" | jq --arg sl "$SESSION_LOG_OVERRIDE" '.session_log = $sl')
    fi

    # Validate
    echo "✅ Validating message..." >&2
    if ! "$SCRIPT_DIR/validate-message.sh" "$context_json"; then
        echo "❌ Validation failed" >&2
        exit 1
    fi

    # Extract fields
    local from to timestamp repo branch session_log taxonomy cwd
    from=$(echo "$context_json" | jq -r '.from')
    to=$(echo "$context_json" | jq -r '.to')
    timestamp=$(echo "$context_json" | jq -r '.timestamp')
    repo=$(echo "$context_json" | jq -r '.repo')
    branch=$(echo "$context_json" | jq -r '.branch')
    session_log=$(echo "$context_json" | jq -r '.session_log')
    taxonomy=$(echo "$context_json" | jq -r '.taxonomy')
    cwd=$(echo "$context_json" | jq -r '.cwd')

    # Create session log if it doesn't exist
    if [[ ! -f "$session_log" ]]; then
        echo "📄 Creating session log..." >&2
        create_session_log "$session_log" "$taxonomy"
    fi

    # Git commit session log (unless --no-commit)
    if [[ "$NO_COMMIT" == false ]] && git rev-parse --git-dir > /dev/null 2>&1; then
        echo "💾 Committing session log..." >&2
        git add "$session_log" 2>/dev/null || true
        if ! git diff --cached --quiet 2>/dev/null; then
            git commit -m "session($CURRENT_AGENT): inter-agent-request - escalating to claude" >/dev/null 2>&1 || true
            echo "✅ Session log committed" >&2
        else
            echo "ℹ️  Session log already committed" >&2
        fi
    fi

    # Generate the formatted message
    local message
    message=$(cat <<EOF
===INTER_AGENT_REQUEST===
FROM: $from
TO: $to
TIMESTAMP: $timestamp
REPO: $repo
BRANCH: $branch
SESSION_LOG: $session_log
TAXONOMY: $taxonomy
CWD: $cwd
REQUEST_TYPE: $REQUEST_TYPE
===END_HEADERS===

QUESTION:
$QUESTION

CONTEXT:
$CONTEXT

===END_REQUEST===
EOF
)

    # Display what we're sending
    cat >&2 <<EOF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📨 SENDING TO CLAUDE (Model: $MODEL)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Request Type: $REQUEST_TYPE
Session Log: $session_log
Question: $QUESTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF

    # Check if claude command exists
    if ! command -v claude &> /dev/null; then
        echo "❌ Error: 'claude' command not found" >&2
        echo "   Install from: github.com/anthropics/claude-code" >&2
        exit 1
    fi

    # Send to Claude with specified model (OPUS by default)
    echo "🚀 Sending to Claude..." >&2
    echo "" >&2

    local response
    response=$(claude --model "$MODEL" -p "$message" 2>&1) || {
        echo "❌ Error: Claude command failed" >&2
        echo "$response" >&2
        exit 1
    }

    # Display response
    cat <<EOF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📥 CLAUDE RESPONSE (Model: $MODEL)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

$response

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
}

# Run main function
main "$@"
