#!/bin/bash
# Codex PreCompact Hook (Bi-directional)
# AUTO-SAVES session state before compaction and returns confirmation.
#
# INPUT: JSON payload via stdin
# OUTPUT: JSON response with hookSpecificOutput.additionalContext
#
# Naming: <owner>--<client>_<domain>_<repo>_<feature>_<YYYYMMDD>_v<N>_codex.md

# Read JSON from stdin
INPUT=$(cat)

TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
DATE_ONLY=$(date '+%Y%m%d')

# Parse JSON payload
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
PROJECT_DIR=$(echo "$INPUT" | jq -r '.cwd // empty')
REASON=$(echo "$INPUT" | jq -r '.hook_event.reason // "unknown"')
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.hook_event.transcript_path // empty')

if [ -z "$PROJECT_DIR" ] || [ ! -d "$PROJECT_DIR" ]; then
  echo '{}' # Return empty response
  exit 0
fi

# Get taxonomy from .claude/taxonomy.json (shared with all agents)
TAXONOMY_FILE="$PROJECT_DIR/.claude/taxonomy.json"

if [ -f "$TAXONOMY_FILE" ]; then
  OWNER=$(jq -r '.owner // "unknown"' "$TAXONOMY_FILE")
  CLIENT=$(jq -r '.client // "unknown"' "$TAXONOMY_FILE")
  DOMAIN=$(jq -r '.domain // "unknown"' "$TAXONOMY_FILE")
  FEATURE=$(jq -r '.feature // "general"' "$TAXONOMY_FILE")
else
  OWNER=$(git -C "$PROJECT_DIR" config user.name 2>/dev/null | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
  if [ -z "$OWNER" ]; then
    OWNER="unknown"
  fi
  CLIENT="unknown"
  DOMAIN="unknown"
  FEATURE="general"
fi

# Get repo name
if [ -f "$TAXONOMY_FILE" ]; then
  REPO=$(jq -r '.repo // empty' "$TAXONOMY_FILE")
fi
if [ -z "$REPO" ]; then
  REPO=$(git -C "$PROJECT_DIR" remote get-url origin 2>/dev/null | sed 's/.*\///' | sed 's/\.git$//')
fi
if [ -z "$REPO" ]; then
  REPO=$(basename "$PROJECT_DIR")
fi

# Ensure session-logs directory exists
SESSION_DIR="$PROJECT_DIR/session-logs"
mkdir -p "$SESSION_DIR"

# Find existing session logs to determine version
EXISTING=$(ls "$SESSION_DIR"/${OWNER}--${CLIENT}_${DOMAIN}_${REPO}_*_v*_codex.md 2>/dev/null | wc -l | tr -d ' ')
OLD_COUNT=$(ls "$SESSION_DIR"/*_session_v*.md 2>/dev/null | wc -l | tr -d ' ')
TOTAL_EXISTING=$((EXISTING + OLD_COUNT))
NEXT_VERSION=$((TOTAL_EXISTING + 1))

# Get previous log for reference
PREV_LOG=$(ls -t "$SESSION_DIR"/${OWNER}--${CLIENT}_${DOMAIN}_${REPO}_*_v*.md 2>/dev/null | head -1)
PREV_LOG_NAME=$(basename "$PREV_LOG" 2>/dev/null || echo "none")

# Agent identifier
AGENT="codex"

# New log filename
NEW_LOG="$SESSION_DIR/${OWNER}--${CLIENT}_${DOMAIN}_${REPO}_${FEATURE}_${DATE_ONLY}_v${NEXT_VERSION}_${AGENT}.md"

# GEMINI SUMMARIZATION: Use Gemini to summarize what Codex was doing
GEMINI_SUMMARY=""
if command -v gemini &> /dev/null; then
  CONTEXT_BLOB="Codex session in $PROJECT_DIR is about to compact its context.
Session ID: $SESSION_ID
Reason: $REASON
Repository: $REPO
Feature: $FEATURE"

  GEMINI_SUMMARY=$(echo "$CONTEXT_BLOB" | gemini -m pro -p "Generate a brief session summary note for a Codex session that is compacting:

## Session Info
- Agent: Codex
- Session ID: $SESSION_ID
- Working Directory: $PROJECT_DIR
- Compaction Reason: $REASON

## Note
This is an auto-generated placeholder. Codex doesn't expose transcripts to hooks.
Check the Codex history file for full context if needed." 2>/dev/null | grep -v "DeprecationWarning" | grep -v "^Hook registry" | grep -v "^Loaded cached")
fi

# AUTO-SAVE: Create session log
{
  echo "# Session Log: ${OWNER}/${CLIENT}/${DOMAIN}/${REPO}"
  echo ""
  echo "**Feature:** ${FEATURE}"
  echo "**Agent:** Codex"
  echo "**Generated:** $(TZ='America/New_York' date '+%Y-%m-%d %H:%M:%S %Z')"
  echo "**Trigger:** ${REASON} compaction"
  echo "**Previous Log:** ${PREV_LOG_NAME}"
  echo ""
  echo "---"
  echo ""
  echo "## TAXONOMY"
  echo ""
  echo "| Level | Value |"
  echo "|-------|-------|"
  echo "| Owner | ${OWNER} |"
  echo "| Client | ${CLIENT} |"
  echo "| Domain | ${DOMAIN} |"
  echo "| Repo | ${REPO} |"
  echo "| Feature | ${FEATURE} |"
  echo "| Session ID | \`${SESSION_ID}\` |"
  echo ""
  echo "---"
  echo ""
  echo "## CONTEXT SUMMARY"
  echo ""
  if [ -n "$GEMINI_SUMMARY" ]; then
    echo "$GEMINI_SUMMARY"
  else
    echo "**Auto-generated by Codex PreCompact hook**"
    echo ""
    echo "- Session ID: \`$SESSION_ID\`"
    echo "- Compaction Reason: $REASON"
    echo "- Working Directory: \`$PROJECT_DIR\`"
  fi
  echo ""
  echo "---"
  echo ""
  echo "## INTER-AGENT PROTOCOL"
  echo ""
  echo "Session logs follow Trifecta naming: \`*_claude.md\`, \`*_codex.md\`, \`*_gemini.md\`"
  echo ""
  echo "---"
  echo ""
  echo "## SESSION ACTIVITY LOG"
  echo ""
  echo "| Time | Action | Outcome |"
  echo "|------|--------|---------|"
  echo "| $(TZ='America/New_York' date '+%H:%M') | PreCompact hook | Created ${NEW_LOG##*/} |"
  echo ""
} > "$NEW_LOG"

# Git commit the auto-save (if in a git repo)
if [ -d "$PROJECT_DIR/.git" ]; then
  cd "$PROJECT_DIR"
  git add "$NEW_LOG" 2>/dev/null
  git commit -m "Auto-save: Codex PreCompact session log ($(TZ='America/New_York' date '+%Y-%m-%d %H:%M'))" 2>/dev/null
fi

# Log success
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Codex PreCompact: Saved $NEW_LOG" >> /tmp/codex-hook.log

# Return confirmation context to inject into the session
CONFIRM_MSG="✅ AUTO-SAVED session log before compaction:
$NEW_LOG
Taxonomy: ${OWNER}/${CLIENT}/${DOMAIN}/${REPO}"

jq -n --arg ctx "$CONFIRM_MSG" '{
  "hookSpecificOutput": {
    "hookEventName": "PreCompact",
    "additionalContext": $ctx
  }
}'

exit 0
